global:
    scrape_interval: 15s

    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: 'kafka-monitor'

scrape_configs:
    - job_name: 'kafka-broker'

      scrape_interval: 5s

      static_configs:
        - targets:
            - kafka1:8091
            - kafka2:8091
            - kafka3:8091
            - kafka4:8091
          labels:
            env: 'dev'

    - job_name: 'kafka-connect'
      scrape_interval: 5s
      static_configs:
        - targets:
            - kafka-connect:8091
          labels:
            env: 'dev'
            kafka_connect_cluster_id: 'connect-cluster'