
############################# Configuracoes Gerais #############################

name=RedisKafkaSinkConnector
connector.class=com.redis.kafka.connect.RedisSinkConnector
redis.server.mode=Standalone
topics=teste
redis.database=0
redis.timeout=60

#################################### Rede ######################################

redis.host=redis
redis.port=6379
redis.uri=redis://redis:6379

################################ Key & Value ####################################

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

redis.command=JSONSET

transforms=createKey,extractKey
transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.createKey.fields=driver_id

transforms.extractKey.type=org.apache.kafka.connect.transforms.ExtractField\$Key
transforms.extractKey.field=driver_id